# Generated by Django 4.2.7 on 2025-09-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('handler_function', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_auth', models.BooleanField(default=True)),
                ('admin_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['command'],
            },
        ),
        migrations.CreateModel(
            name='BotWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('secret_token', models.CharField(blank=True, max_length=100)),
                ('last_update_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('document', 'Document'), ('voice', 'Voice'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact', 'Contact')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('is_bot_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_to_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.botmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram_bot.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('waiting_for_input', 'Waiting for Input'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='idle', max_length=30)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='telegram_bot.telegramuser')),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='BotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_received', models.PositiveIntegerField(default=0)),
                ('commands_executed', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='telegram_bo_date_688b36_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['telegram_id'], name='telegram_bo_telegra_a470eb_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['username'], name='telegram_bo_usernam_30d6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['user', 'created_at'], name='telegram_bo_user_id_197562_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['message_type'], name='telegram_bo_message_22b151_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessage',
            index=models.Index(fields=['is_bot_message'], name='telegram_bo_is_bot__42ab70_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['user', 'state'], name='telegram_bo_user_id_5ad7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='botconversation',
            index=models.Index(fields=['last_activity'], name='telegram_bo_last_ac_7b7d5e_idx'),
        ),
    ]
